apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graphql
spec:
  selector:
    matchLabels:
      app: api-graphql
  template:
    metadata:
      labels:
        app: api-graphql
    spec:
      containers:
      - name: api-graphql
        image: api-graphql-nodejs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-graphql
spec:
  type: NodePort
  selector:
    app: api-graphql
  ports:
  - port: 8080
    targetPort: 8080

